{
 "title": "Helium",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hotspotname",
    "label": "Hotspot Name",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"name\",\n    predicate: (r) => true)"
   }
  ]
 },
 "panels": [
  { "title": "Status of ${hotspotname}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hotspotname" },
  {
   "title": "Daily Rewards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> timeShift(duration: -4h)\n  |> aggregateWindow(every: 1d, fn: sum, timeSrc: \"_start\", createEmpty: true)\n  |> timeShift(duration: 4h)\n  |> yield(name: \"rewards\")\n\nfrom(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"beacon_received\")\n  |> filter(fn: (r) => r[\"_field\"] == \"witnesses\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> timeShift(duration: -4h)\n  |> aggregateWindow(every: 1d, fn: count, timeSrc: \"_start\", createEmpty: true)\n  |> timeShift(duration: 4h)\n  |> yield(name: \"beacons\")"
    }
   ]
  },
  {
   "title": "Rewards (8h moving)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "targets": [
    {
     "query": "timedMovingSum = (every, period, column=\"_value\", tables=<-) =>\n  tables\n    |> window(every: every, period: period)\n    |> sum(column:column)\n    |> duplicate(column: \"_stop\", as: \"_time\")\n    |> window(every: inf)\n\nfrom(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> timedMovingSum(every: 1h, period: 8h)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "24hr rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> set(key: \"_field\", value: \"24hr\")\n  |> yield(name: \"24hr\")\n\n  from(bucket: \"dashboard\")\n  |> range(start: -48h, stop: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> set(key: \"_field\", value: \"prev\")\n  |> yield(name: \"prev\")\n"
    }
   ]
  },
  {
   "title": "7d rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: -1w)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> set(key: \"_field\", value: \"1w\")\n  |> yield(name: \"1w\")\n\n  from(bucket: \"dashboard\")\n  |> range(start: -2w, stop: -1w)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> set(key: \"_field\", value: \"prev\")\n  |> yield(name: \"prev\")\n"
    }
   ]
  },
  {
   "title": "30d rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> set(key: \"_field\", value: \"30d\")\n  |> yield(name: \"30d\")\n\n  from(bucket: \"dashboard\")\n  |> range(start: -60d, stop: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> set(key: \"_field\", value: \"prev\")\n  |> yield(name: \"prev\")\n"
    }
   ]
  },
  {
   "title": "Last Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> last()\n  |> duplicate(column: \"_time\", as: \"last\")\n  |> keep(columns: [\"type\", \"last\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Last Election",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.data[0].time", "type": "time" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Hourly Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"rewards\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> aggregateWindow(every: 1h, fn: sum, timeSrc: \"_start\", createEmpty: true)\n  |> yield(name: \"rewards\")\n\nfrom(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"beacon_received\")\n  |> filter(fn: (r) => r[\"_field\"] == \"witnesses\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> aggregateWindow(every: 1h, fn: count, timeSrc: \"_start\", createEmpty: true)\n  |> yield(name: \"beacons\")"
    }
   ]
  },
  {
   "title": "Witnesses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"beacon_sent\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  //|> aggregateWindow(every: 1h, fn: sum, timeSrc: \"_start\", createEmpty: true)\n  |> yield(name: \"beacons\")"
    }
   ]
  },
  {
   "title": "Helium Price (USD)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_price\")\n  |> filter(fn: (r) => r[\"_field\"] == \"USD\")\n  |> filter(fn: (r) => r[\"source\"] == \"CoinGecko\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Helium (USD)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_price\")\n  |> filter(fn: (r) => r[\"_field\"] == \"USD\")\n  |> filter(fn: (r) => r[\"source\"] == \"CoinGecko\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Challenges",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"challenge\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> aggregateWindow(every: 1h, fn: sum, timeSrc: \"_start\", createEmpty: true)\n  |> yield(name: \"challenges\")"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"challenges\")\n  //|> aggregateWindow(every: 1h, fn: sum, timeSrc: \"_start\", createEmpty: true)\n  |> difference()\n  |> timedMovingAverage(every: 10m, period: 1h)\n  |> yield(name: \"data\")\n\n"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"data_transfer\")\n  |> filter(fn: (r) => r[\"name\"] == \"${hotspotname}\")\n  |> aggregateWindow(every: 1h, fn: sum, timeSrc: \"_start\", createEmpty: true)\n  |> fill(value: 0)\n  |> yield(name: \"data\")"
    }
   ]
  },
  {
   "title": "To Do",
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 20 },
   "options": {
    "content": "* Flag invalid beacons\n* Move Helium price out of the rows"
   }
  }
 ]
}